export const USAGE_OPTIONS = [
  "Administrasi, IT, dan komunikasi",
  "Fasilitas ruangan dan furniture",
  "Kelistrikan, utilitas, dan tata udara",
  "Keamanan, keselamatan, dan tanggap darurat",
  "Logistik, penyimpanan, dan distribusi",
  "Kebersihan, sanitasi, dan pengelolaan limbah",
  "Dapur, laundry, dan layanan penunjang",
  "Transportasi dan operasional lapangan",
  "Operasional bersama",
  "Fasilitas umum",
  "Pendukung klinis",
  "Office administrasi",
  "Kebersihan sanitasi",
  "Keamanan keselamatan",
] as const
