export const USAGE_OPTIONS = [
  "Admin",
  "Fasilitas",
  "Utilitas",
  "Keamanan",
  "Logistik",
  "Kebersihan",
  "Dapur",
  "Transportasi",
  "Operasional",
  "Klinis",
] as const

export const USAGE_PURPOSE_ALIASES: Record<string, (typeof USAGE_OPTIONS)[number]> = {
  "Administrasi & Komunikasi": "Admin",
  "Administrasi dan Komunikasi": "Admin",
  "Administrasi, IT, dan komunikasi": "Admin",
  "Office administrasi": "Admin",
  "Fasilitas & Furnitur": "Fasilitas",
  "Fasilitas dan Furnitur": "Fasilitas",
  "Fasilitas ruangan dan furniture": "Fasilitas",
  "Fasilitas umum": "Fasilitas",
  "Utilitas & Tata Udara": "Utilitas",
  "Utilitas dan Tata Udara": "Utilitas",
  "Kelistrikan, utilitas, dan tata udara": "Utilitas",
  "Keamanan & Darurat": "Keamanan",
  "Keamanan dan Darurat": "Keamanan",
  "Keamanan, keselamatan, dan tanggap darurat": "Keamanan",
  "Keamanan keselamatan": "Keamanan",
  "Logistik & Penyimpanan": "Logistik",
  "Logistik dan Penyimpanan": "Logistik",
  "Logistik, penyimpanan, dan distribusi": "Logistik",
  "Kebersihan & Limbah": "Kebersihan",
  "Kebersihan dan Limbah": "Kebersihan",
  "Kebersihan, sanitasi, dan pengelolaan limbah": "Kebersihan",
  "Kebersihan sanitasi": "Kebersihan",
  "Dapur, Laundry & Penunjang": "Dapur",
  "Dapur, Laundry dan Penunjang": "Dapur",
  "Dapur, laundry, dan layanan penunjang": "Dapur",
  "Transportasi Operasional": "Transportasi",
  "Transportasi dan operasional lapangan": "Transportasi",
  "Operasional bersama": "Operasional",
  "Pendukung klinis": "Klinis",
}
