export const MEDICAL_USAGE_OPTIONS = [
  "Rawat Inap",
  "Pemeriksaan",
  "Diagnostik",
  "Tindakan",
  "Terapi",
  "ICU",
  "Bedah",
  "Ibu dan Bayi",
  "Hemodialisis",
  "Lab",
  "Rehabilitasi",
  "Operasional",
  "Tim Medis",
] as const

export const MEDICAL_USAGE_ALIASES: Record<string, (typeof MEDICAL_USAGE_OPTIONS)[number]> = {
  "Perawatan & Rawat Inap": "Rawat Inap",
  "Perawatan dan Rawat Inap": "Rawat Inap",
  "Perawatan pasien dan dukungan ruang rawat": "Rawat Inap",
  "Pemeriksaan & Monitoring": "Pemeriksaan",
  "Pemeriksaan dan Monitoring": "Pemeriksaan",
  "Monitoring pasien dan pemeriksaan klinis": "Pemeriksaan",
  "Diagnostik & Pencitraan": "Diagnostik",
  "Diagnostik dan Pencitraan": "Diagnostik",
  "Diagnostik, pencitraan, dan analisis medis": "Diagnostik",
  "Spesialistik & Tindakan": "Tindakan",
  "Spesialistik dan Tindakan": "Tindakan",
  "Pemeriksaan spesialistik dan tindakan klinis": "Tindakan",
  "Terapi & Dukungan Hidup": "Terapi",
  "Terapi dan Dukungan Hidup": "Terapi",
  "Terapi, perawatan, dan dukungan hidup": "Terapi",
  "ICU & Dukungan Kritis": "ICU",
  "ICU dan Dukungan Kritis": "ICU",
  "Monitoring intensif dan dukungan hidup kritis": "ICU",
  "Bedah & Sterilisasi": "Bedah",
  "Bedah dan Sterilisasi": "Bedah",
  "Tindakan bedah dan prosedur steril": "Bedah",
  "Ibu, Bayi & Neonatal": "Ibu dan Bayi",
  "Ibu, Bayi dan Neonatal": "Ibu dan Bayi",
  "Pelayanan ibu, bayi, dan neonatal": "Ibu dan Bayi",
  "Hemodialisis dan terapi penunjang ginjal": "Hemodialisis",
  "Lab, Farmasi & Sampel": "Lab",
  "Lab, Farmasi dan Sampel": "Lab",
  "Laboratorium, farmasi, dan pengolahan sampel": "Lab",
  "Rehabilitasi & Mobilisasi": "Rehabilitasi",
  "Rehabilitasi dan Mobilisasi": "Rehabilitasi",
  "Rehabilitasi medik dan mobilisasi pasien": "Rehabilitasi",
}
