export interface MedicalAssetCategory {
  description: string
  assetTypes: string[]
}

export const MEDICAL_ASSET_CATEGORIES: Record<string, MedicalAssetCategory> = {
  Medis: {
    description: "",
    assetTypes: [
      "Ambu Bag / Bag Valve Mask (BVM)",
      "Ambu Bag Neonatal",
      "Anesthesia Machine",
      "Anesthesia Monitor",
      "Anesthesia Ventilator",
      "Anesthesia Workstation",
      "Anti-Fall Monitoring System",
      "Apheresis Machine",
      "Arthroscope",
      "Audiometer",
      "Auto Refractometer",

      "Baby Resuscitation Unit",
      "Balance Trainer System",
      "Bed Exit Alarm",
      "Bed Scale (ICU Integrated)",
      "Bedside Cabinet (Lemari Pasien)",
      "Bedside Commode/Urinal (penunjang)",
      "BiPAP",
      "Biological Safety Cabinet (Kemoterapi)",
      "Biosafety Cabinet (Lab)",
      "Blood Bag Sealer",
      "Blood Bank Refrigerator",
      "Blood Culture System",
      "Blood Gas Analyzer (akses NICU/POCT)",
      "Blood Gas Analyzer (POCT bila ada)",
      "Blood Irradiator",
      "Blood Thawing System",
      "Blood Warmer (bila digunakan)",
      "Bowie-Dick Test System",
      "Brain Oxygen Monitor",

      "C-Arm Imaging",
      "Capnography Monitor",
      "Cardiac Output Monitor",
      "CBCT Dental",
      "Central Monitoring System",
      "Central Monitoring System (NICU)",
      "Central Monitoring System (jika ada)",
      "Centrifuge (Lab & Blood Bank)",
      "Chemical & Biological Indicator Reader",
      "Chemotherapy Chair / Bed Kemoterapi",
      "Clinical Chemistry Analyzer",
      "Closed Suction System",
      "Coblator System",
      "Coagulation Analyzer (Lab)",
      "CPAP",
      "Cryostat",
      "CTG (Cardiotocography)",

      "Defibrillator AED",
      "Defibrillator AED (area rawat inap tertentu)",
      "Defibrillator AED/Manual (sesuai kebijakan unit)",
      "Defibrillator Manual",
      "Delivery Bed / Bed Persalinan",
      "Dental Autoclave",
      "Dental Suction System",
      "Dental Unit",
      "Dental X-Ray",
      "Dialysate Mixing System (jika terpisah)",
      "Digital Consent System (Bedside)",
      "Digital Pathology Scanner",
      "Diathermy Machine",
      "Doppler Fetal",
      "Drying Cabinet Endoscope",

      "ECG/EKG (12 lead)",
      "ECG/EKG (portable/bedside)",
      "ECMO Machine (bila RS memiliki)",
      "ECMO System",
      "EEG System",
      "ELISA Reader & Washer",
      "EMG / Nerve Conduction Study",
      "Emergency Bed / Stretcher Bed",
      "Emergency Crash Cart",
      "Emergency Crash Cart (obstetri)",
      "Emergency Crash Cart (OK)",
      "Emergency Set (oksigen portable + ambu bag)",
      "Endoscope Reprocessor (AER)",
      "Endoscopic Camera System",
      "Endoscopy ENT Tower",
      "ENT Examination Unit",
      "ENT Microscope",

      "Fetal Monitor",
      "Fluid Warmer",
      "Fundus Camera",

      "Gait Trainer",
      "Gas Analyzer (anestesi/ICU tertentu)",
      "GeneXpert System",
      "Glucometer",

      "HbA1c Analyzer",
      "Hearing Screening Device (OAE/ABR)",
      "Hematology Analyzer (3-part / 5-part)",
      "Hemodialysis Chair / Bed HD",
      "Hemodialysis Machine",
      "Hemodynamic Monitoring System",
      "Hemoglobinometer",
      "HFNC (High Flow Nasal Cannula)",
      "HFNC Neonatal (jika tersedia)",
      "Hospital Bed / Tempat Tidur Pasien (Manual/Electric)",

      "IABP (Intra-Aortic Balloon Pump)",
      "ICU Bed",
      "ICU Ceiling Pendant (Gas & Electric)",
      "ICU Patient Monitor (multi-parameter)",
      "Immunoassay Analyzer",
      "Infant Incubator",
      "Infant Scale",
      "Infant Warmer",
      "Infusion Pump",
      "Infusion Pump (neonatal compatible)",
      "Instrument Set Cito (set laparotomi/ortopedi/trauma)",
      "Instrument Set Jahit Perineum",
      "Instrument Tracking System (RFID)",
      "Intracranial Pressure Monitor (ICP)",
      "Insufflator CO₂",
      "Isolation Room Pressure Monitor",
      "IV Pole / Tiang Infus",

      "Laminar Air Flow / Biological Safety Cabinet (untuk penyiapan obat, jika berada di unit)",
      "Laparoscope",
      "Laparoscopy Tower",
      "Laryngoscope Set",

      "Maternal Patient Monitor",
      "Medical Examination Bed / Bed Periksa",
      "Medical Examination Lamp (lampu periksa)",
      "Medical Gas Alarm System",
      "Medical Refrigerator (Drug/Vaccine)",
      "Medication Cart (Locked)",
      "Microsurgery Instrument Set",
      "Microbiology Incubator",
      "Microtome",
      "Mobile Workstation on Wheels (WOW)",

      "Neonatal CPAP",
      "Neonatal ICU Bed / Incubator Intensive",
      "Neonatal Monitor",
      "Neonatal Ventilator",
      "Nebulizer",
      "Neuro Navigation System",
      "Nurse Call System",

      "OCT (Optical Coherence Tomography)",
      "Operating Lamp (Shadowless)",
      "Operating Microscope (Eye)",
      "Operating Table",
      "Ophthalmoscope",
      "Otoscope",
      "Oxygen Blender (jika ada)",
      "Oxygen Concentrator (bila ada)",
      "Oxygen Cylinder + Regulator (portable)",
      "Oxygen Flowmeter & Humidifier",
      "Oxygen Flowmeter Neonatal",

      "Panoramic X-Ray (OPG)",
      "Parallel Bar",
      "Pass-Through Autoclave",
      "Patient Fall Detection System",
      "Patient Hoist / Lifter",
      "Patient Monitor (ECG/NIBP/SpO2/Temp)",
      "Patient Monitor (HD/bedside monitor)",
      "Patient Monitor (bedside) / Monitor Tanda Vital",
      "PCR Analyzer (Real-Time PCR)",
      "Pelvic Binder",
      "Phacoemulsification System",
      "Phototherapy Unit",
      "Phototherapy Unit (bila area bayi dekat)",
      "Plasma Freezer (-30°C / -80°C)",
      "Portable Anesthesia Workstation",
      "Portable Oxygen Cylinder",
      "Portable Ventilator",
      "Portable X-Ray (akses area bedah)",
      "Portable X-Ray (jika tersedia di IGD)",
      "Pressure Ulcer Prevention System",
      "Pulse Oximeter",
      "Pulse Oximeter Neonatal",

      "Rapid Infuser (jika ada)",
      "Refrigerator Monitoring System (Vaccine/Drug)",
      "Reflex Hammer",
      "Robotic Gait Training System",

      "Scales / Timbangan Pasien (pre-post HD)",
      "Slide Stainer (H&E / IHC)",
      "Slit Lamp",
      "Smart IV Pole",
      "Smart Patient ID Wristband System",
      "Spine Board & Cervical Collar (penunjang IGD)",
      "Standing Frame",
      "Steam Generator Autoclave",
      "Sterile Storage Cabinet (HEPA)",
      "Stethoscope",
      "Suction Pump (portable)",
      "Suction Pump (portable & wall suction)",
      "Suction Unit Neonatal",
      "Surgical Instrument Set (major/minor)",
      "Surgical Suction System",
      "Syringe Pump",
      "Syringe Pump (neonatal)",

      "TCD (Transcranial Doppler)",
      "Telemedicine Cart",
      "Temperature & Humidity Monitoring (Pharmacy/CSSD)",
      "Thermometer Digital/Infrared",
      "Thermometer Neonatal",
      "Tissue Processor",
      "Trolley Obat/Tindakan",
      "Trolley Resusitasi Bayi",
      "Trolley Tindakan",
      "Trolley Tindakan/Obat",
      "Tuning Fork",
      "Tympanometer",

      "Ultrasonic Scaler",
      "UPS Medical Grade",
      "Urine Analyzer",
      "USG (portable/ruang kebidanan bila ada)",
      "USG Bedside / POCUS (Point-of-Care Ultrasound)",

      "Vacuum Extractor",
      "Ventilator (anestesi/portable)",
      "Ventilator ICU",
      "Ventilator Transport",
      "Video Laryngoscope",
      "Visual Field Analyzer",

      "Warming Cabinet (Blanket/Fluid)",
      "Water Treatment System (RO) untuk HD)",
      "Wheelchair Medical Grade",
      "YAG Laser",
    ],
  },
}